export { default as Facebook } from "./facebook"
export { default as LinkedIn } from "./linkedIn"
export { default as X } from "./x"
export { default as Github } from "./github"
export { default as Browser } from "./browser"